on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - "14"
          - "16"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - run: npm install
      - run: npm run build
